vich_uploader:
    db_driver: orm

    mappings:
        foo_bars:
            uri_prefix: /bars
            upload_destination: '%kernel.project_dir%/public/bars'
            namer: Vich\UploaderBundle\Naming\HashNamer
